version: 2.1
orbs:
  node: circleci/node@1.1
executors:
  java-executor:
    docker:
      - image: circleci/openjdk
    working_directory: /go/src/github.com/lacework/go-sdk
jobs:
  build:
    executor: java-executor
    steps:
      - checkout
      - run: mvn -v
